/* ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison G. Watson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 *
 * ACS string table.
 *
 * ---------------------------------------------------------------------------|
 */

#if defined(stab_x)

stab_x(st_nil, "")

/* Font Names */
stab_x(sf_areaname, "areaname")
stab_x(sf_bigupper, "bigupper")
stab_x(sf_lsmlhfnt, "lsmlhfnt")
stab_x(sf_lmidfont, "lmidfont")
stab_x(sf_ltrmfont, "ltrmfont")
stab_x(sf_smallfnt, "smallfnt")

/* Console Variables */
stab_x(sc_debug_level,            DCVAR "debug_level")
stab_x(sc_debug_flags,            DCVAR "debug_flags")
stab_x(sc_fun,                    DCVAR "fun")
stab_x(sc_gui_buyfiller,          CVAR "gui_buyfiller")
stab_x(sc_gui_cursor,             CVAR "gui_cursor")
stab_x(sc_gui_defcr,              CVAR "gui_defcr")
stab_x(sc_gui_theme,              CVAR "gui_theme")
stab_x(sc_gui_xmul,               CVAR "gui_xmul")
stab_x(sc_gui_ymul,               CVAR "gui_ymul")
stab_x(sc_hud_expbar,             CVAR "hud_expbar")
stab_x(sc_hud_logfromtop,         CVAR "hud_logfromtop")
stab_x(sc_hud_logsize,            CVAR "hud_logsize")
stab_x(sc_hud_showarmorind,       CVAR "hud_showarmorind")
stab_x(sc_hud_showlog,            CVAR "hud_showlog")
stab_x(sc_hud_showlvl,            CVAR "hud_showlvl")
stab_x(sc_hud_showscore,          CVAR "hud_showscore")
stab_x(sc_hud_showweapons,        CVAR "hud_showweapons")
stab_x(sc_k_opencbi,              CVAR "k_opencbi")
stab_x(sc_light_battery,          CVAR "light_battery")
stab_x(sc_light_regen,            CVAR "light_regen")
stab_x(sc_player_ammolog,         CVAR "player_ammolog")
stab_x(sc_player_bosstexts,       CVAR "player_bosstexts")
stab_x(sc_player_damagebob,       CVAR "player_damagebob")
stab_x(sc_player_damagebobmul,    CVAR "player_damagebobmul")
stab_x(sc_player_footstepvol,     CVAR "player_footstepvol")
stab_x(sc_player_invertmouse,     CVAR "player_invertmouse")
stab_x(sc_player_lvsys,           CVAR "player_lvsys")
stab_x(sc_player_resultssound,    CVAR "player_resultssound")
stab_x(sc_player_scorelog,        CVAR "player_scorelog")
stab_x(sc_player_scoresound,      CVAR "player_scoresound")
stab_x(sc_player_stupidpickups,   CVAR "player_stupidpickups")
stab_x(sc_player_teleshop,        CVAR "player_teleshop")
stab_x(sc_player_viewtilt,        CVAR "player_viewtilt")
stab_x(sc_psave,                  CVAR "psave")
stab_x(sc_scanner_altfont,        CVAR "scanner_altfont")
stab_x(sc_scanner_bar,            CVAR "scanner_bar")
stab_x(sc_scanner_color,          CVAR "scanner_color")
stab_x(sc_scanner_slide,          CVAR "scanner_slide")
stab_x(sc_scanner_xoffs,          CVAR "scanner_xoffs")
stab_x(sc_scanner_yoffs,          CVAR "scanner_yoffs")
stab_x(sc_sv_minhealth,           CVAR "sv_minhealth")
stab_x(sc_sv_autosave,            CVAR "sv_autosave")
stab_x(sc_sv_difficulty,          CVAR "sv_difficulty")
stab_x(sc_sv_failtime,            CVAR "sv_failtime")
stab_x(sc_sv_nobossdrop,          CVAR "sv_nobossdrop")
stab_x(sc_sv_nobosses,            CVAR "sv_nobosses")
stab_x(sc_sv_rain,                CVAR "sv_rain")
stab_x(sc_sv_revenge,             CVAR "sv_revenge")
stab_x(sc_sv_scoremul,            CVAR "sv_scoremul")
stab_x(sc_sv_sky,                 CVAR "sv_sky")
stab_x(sc_sv_wepdrop,             CVAR "sv_wepdrop")
stab_x(sc_version,                DCVAR "version")
stab_x(sc_weapons_magicselanims,  CVAR "weapons_magicselanims")
stab_x(sc_weapons_riflemodeclear, CVAR "weapons_riflemodeclear")
stab_x(sc_weapons_riflescope,     CVAR "weapons_riflescope")
stab_x(sc_weapons_slot3ammo,      CVAR "weapons_slot3ammo")
stab_x(sc_weapons_zoomfactor,     CVAR "weapons_zoomfactor")
stab_x(sc_xhair_style,            CVAR "xhair_style")

/* Methods / Members */
stab_x(sm_AdrenalineCheck,    "AdrenalineCheck")
stab_x(sm_AlertMonsters,      "AlertMonsters")
stab_x(sm_AutoReload,         "AutoReload")
stab_x(sm_CheckLump,          "CheckLump")
stab_x(sm_DelearSprite,       "DelearSprite")
stab_x(sm_DeleteItem,         "DeleteItem")
stab_x(sm_DieMonster,         "DieMonster")
stab_x(sm_DieNow,             "DieNow")
stab_x(sm_DmgFac,             "m_DmgFac")
stab_x(sm_FindFontColor,      "FindFontColor")
stab_x(sm_FindLump,           "FindLump")
stab_x(sm_ForceDraw,          "ForceDraw")
stab_x(sm_FxTID,              "m_FxTID")
stab_x(sm_GetAttackHeight,    "GetAttackHeight")
stab_x(sm_GetBipName,         "GetBipName")
stab_x(sm_GetBossLevel,       "GetBossLevel")
stab_x(sm_GetCurMag,          "GetCurMag")
stab_x(sm_GetLogName,         "GetLogName")
stab_x(sm_GetMaxMag,          "GetMaxMag")
stab_x(sm_GetObituary,        "GetObituary")
stab_x(sm_GetOutOfDodge,      "GetOutOfDodge")
stab_x(sm_GetPaused,          "GetPaused")
stab_x(sm_GetRifleGrenade,    "GetRifleGrenade")
stab_x(sm_GetSpawnHealth,     "GetSpawnHealth")
stab_x(sm_GetViewHeight,      "GetViewHeight")
stab_x(sm_GivePoison,         "GivePoison")
stab_x(sm_GrabInput,          "m_GrabInput")
stab_x(sm_Health,             "Health")
stab_x(sm_Height,             "Height")
stab_x(sm_InvName,            "m_InvName")
stab_x(sm_IonizeFX,           OBJ "IonizeFX")
stab_x(sm_IsRampancy,         "IsRampancy")
stab_x(sm_JumpZ,              "JumpZ")
stab_x(sm_LC,                 "LC")
stab_x(sm_LE,                 "LE")
stab_x(sm_LF,                 "LF")
stab_x(sm_LL,                 "LL")
stab_x(sm_LR,                 "LR")
stab_x(sm_LS,                 "LS")
stab_x(sm_LT,                 "LT")
stab_x(sm_LX,                 "LX")
stab_x(sm_LY,                 "LY")
stab_x(sm_LZ,                 "LZ")
stab_x(sm_MapNoRain,          "user_" OBJ "NoRain")
stab_x(sm_MapUseRain,         "user_" OBJ "UseRain")
stab_x(sm_MonsterBarrierLook, "MonsterBarrierLook")
stab_x(sm_Nuke,               "Nuke")
stab_x(sm_OnGround,           "m_OnGround")
stab_x(sm_Overdrive,          "m_Overdrive")
stab_x(sm_PhantomOut,         "PhantomOut")
stab_x(sm_PhantomTeleport,    "PhantomTeleport")
stab_x(sm_PlayerDeath,        "PlayerDeath")
stab_x(sm_PlayerDeathNuke,    "PlayerDeathNuke")
stab_x(sm_PlayerInit,         "PlayerInit")
stab_x(sm_PoisonFX,           "PoisonFX")
stab_x(sm_Project,            "Project")
stab_x(sm_PureSteggleEnergy,  "PureSteggleEnergy")
stab_x(sm_Radius,             "Radius")
stab_x(sm_ReadLump,           "ReadLump")
stab_x(sm_Set,                "Set")
stab_x(sm_SetFrozen,          "SetFrozen")
stab_x(sm_SetTeleFogTo,       "SetTeleFogTo")
stab_x(sm_SpawnBoss,          "SpawnBoss")
stab_x(sm_SpawnRain,          "SpawnRain")
stab_x(sm_Speed,              "Speed")
stab_x(sm_StartSound,         "StartSound")
stab_x(sm_SurgeOfDestiny,     "SurgeOfDestiny")
stab_x(sm_TraceFrom,          "TraceFrom")
stab_x(sm_Trigger,            "m_Trigger")
stab_x(sm_TriggerBoss,        "TriggerBoss")
stab_x(sm_UpgradeBody,        "m_UpgradeBody")
stab_x(sm_UpgradeExtr,        "m_UpgradeExtr")
stab_x(sm_UpgradeId,          "m_UpgradeId")
stab_x(sm_UpgradeWeap,        "m_UpgradeWeap")
stab_x(sm_UseItem,            "UseItem")
stab_x(sm_UserX,              "user_X")
stab_x(sm_UserY,              "user_Y")
stab_x(sm_UserZ,              "user_Z")
stab_x(sm_WaterLevel,         "WaterLevel")

/* Objects */
stab_x(so_AssassinPlayer,      OBJ "AssassinPlayer")
stab_x(so_BarrierFX,           OBJ "BarrierFX")
stab_x(so_Blade,               OBJ "Blade")
stab_x(so_BloodRainDrop,       OBJ "BloodRainDrop")
stab_x(so_BossReward1,         OBJ "BossReward1")
stab_x(so_BossReward2,         OBJ "BossReward2")
stab_x(so_BossReward3,         OBJ "BossReward3")
stab_x(so_BossReward4,         OBJ "BossReward4")
stab_x(so_BossReward5,         OBJ "BossReward5")
stab_x(so_BossReward6,         OBJ "BossReward6")
stab_x(so_BoughtItem,          OBJ "BoughtItem")
stab_x(so_CameraHax,           OBJ "CameraHax")
stab_x(so_CannonAmmo,          OBJ "CannonAmmo")
stab_x(so_Cercle,              OBJ "Cercle")
stab_x(so_CircleParticle,      OBJ "CircleParticle")
stab_x(so_CircleSpearThrower,  OBJ "CircleSpearThrower")
stab_x(so_ClawOfImp,           OBJ "ClawOfImp")
stab_x(so_CyberMagePlayer,     OBJ "CyberMagePlayer")
stab_x(so_DarkLordPlayer,      OBJ "DarkLordPlayer")
stab_x(so_Delear,              OBJ "Delear")
stab_x(so_Draw,                OBJ "URANUS")
stab_x(so_Dummy,               OBJ "Dummy")
stab_x(so_EXPLOOOSION,         OBJ "EXPLOOOSION")
stab_x(so_ExplodoBoots,        OBJ "ExplodoBoots")
stab_x(so_Feuer,               OBJ "Feuer")
stab_x(so_FeuerExplosion,      OBJ "FeuerExplosion")
stab_x(so_FeuerFinal,          OBJ "FeuerFinal")
stab_x(so_FeuerTest,           OBJ "FeuerTest")
stab_x(so_FistCharge,          OBJ "FistCharge")
stab_x(so_GEExplosion,         OBJ "GEExplosion")
stab_x(so_GTFO,                OBJ "GTFO")
stab_x(so_Hulgyon,             OBJ "Hulgyon")
stab_x(so_InformantPlayer,     OBJ "InformantPlayer")
stab_x(so_Ionized,             OBJ "Ionized")
stab_x(so_Mana,                OBJ "Mana")
stab_x(so_ManaLeak,            OBJ "ManaLeak")
stab_x(so_ManaPickup,          OBJ "ManaPickup")
stab_x(so_MarinePlayer,        OBJ "MarinePlayer")
stab_x(so_MegaProtection,      OBJ "MegaProtection")
stab_x(so_MonsterBarrier,      OBJ "MonsterBarrier")
stab_x(so_MonsterHeptaura,     OBJ "MonsterHeptaura")
stab_x(so_MonsterID,           OBJ "MonsterID")
stab_x(so_MonsterLevelUp,      OBJ "MonsterLevelUp")
stab_x(so_MonsterSoul,         OBJ "MonsterSoul")
stab_x(so_PlasmaAmmo,          OBJ "PlasmaAmmo")
stab_x(so_Player,              OBJ "Player")
stab_x(so_PoisonFXReset,       OBJ "PoisonFXReset")
stab_x(so_PoisonFXTimer,       OBJ "PoisonFXTimer")
stab_x(so_PowerStrength,       "PowerStrength")
stab_x(so_PunctuatorExplosion, OBJ "PunctuatorExplosion")
stab_x(so_PunctuatorPuff,      OBJ "PunctuatorPuff")
stab_x(so_RainDrop,            OBJ "RainDrop")
stab_x(so_RandomSpawn,         OBJ "RandomSpawn")
stab_x(so_Rend,                OBJ "Rend")
stab_x(so_RocketAmmo,          OBJ "RocketAmmo")
stab_x(so_RocketBooster,       OBJ "RocketBooster")
stab_x(so_SMGHeat,             OBJ "SMGHeat")
stab_x(so_Serv,                OBJ "HERMES")
stab_x(so_ShellAmmo,           OBJ "ShellAmmo")
stab_x(so_StarShot,            OBJ "StarShot")
stab_x(so_StealthSystem,       OBJ "StealthSystem")
stab_x(so_Steggles,            OBJ "Steggles")
stab_x(so_Sword,               OBJ "Sword")
stab_x(so_TargetMarker,        OBJ "TargetMarker")
stab_x(so_TeleFog5,            OBJ "TeleFog5")
stab_x(so_TeleFog6,            OBJ "TeleFog6")
stab_x(so_TeleFog7,            OBJ "TeleFog7")
stab_x(so_ThothPlayer,         OBJ "ThothPlayer")
stab_x(so_UniqueID,            OBJ "UniqueID")
stab_x(so_WandererPlayer,      OBJ "WandererPlayer")
stab_x(so_WeaponScopedToken,   OBJ "WeaponScopedToken")

/* Paths */
stab_x(sp_Dialogue_Back,        ":Dialogue:Back")
stab_x(sp_HUD_C_BarSmall,       ":HUD_C:BarSmall")
stab_x(sp_HUD_C_BarSmall2,      ":HUD_C:BarSmall2")
stab_x(sp_HUD_C_MagicIcon,      ":HUD_C:MagicIcon")
stab_x(sp_HUD_C_ManaBar1,       ":HUD_C:ManaBar1")
stab_x(sp_HUD_C_ManaBar2,       ":HUD_C:ManaBar2")
stab_x(sp_HUD_H_B3,             ":HUD:H_B3")
stab_x(sp_HUD_H_C1,             ":HUD:H_C1")
stab_x(sp_HUD_H_C2,             ":HUD:H_C2")
stab_x(sp_HUD_H_D14,            ":HUD:H_D14")
stab_x(sp_HUD_H_D16,            ":HUD:H_D16")
stab_x(sp_HUD_H_D21,            ":HUD:H_D21")
stab_x(sp_HUD_H_D24,            ":HUD:H_D24")
stab_x(sp_HUD_H_D41,            ":HUD:H_D41")
stab_x(sp_HUD_H_D44,            ":HUD:H_D44")
stab_x(sp_HUD_H_D46,            ":HUD:H_D46")
stab_x(sp_HUD_H_KC1,            ":HUD:H_KC1")
stab_x(sp_HUD_H_KC2,            ":HUD:H_KC2")
stab_x(sp_HUD_H_KC3,            ":HUD:H_KC3")
stab_x(sp_HUD_H_KS1,            ":HUD:H_KS1")
stab_x(sp_HUD_H_KS2,            ":HUD:H_KS2")
stab_x(sp_HUD_H_KS3,            ":HUD:H_KS3")
stab_x(sp_HUD_H_W3,             ":HUD:H_W3")
stab_x(sp_Terminal_Teleport,    ":Terminal:Teleport")
stab_x(sp_UI_AttrBar1,          ":UI:AttrBar1")
stab_x(sp_UI_AttrBar2,          ":UI:AttrBar2")
stab_x(sp_UI_AttrBar4,          ":UI:AttrBar4")
stab_x(sp_UI_Bag,               ":UI:Bag")
stab_x(sp_UI_Body,              ":UI:Body")
stab_x(sp_UI_Cursor,            ":UI:Cursor")
stab_x(sp_UI_CursorBlue,        ":UI:CursorBlue")
stab_x(sp_UI_CursorOrange,      ":UI:CursorOrange")
stab_x(sp_UI_CursorOutline,     ":UI:CursorOutline")
stab_x(sp_UI_CursorOutline2,    ":UI:CursorOutline2")
stab_x(sp_UI_CursorOutline2Inv, ":UI:CursorOutline2Inv")
stab_x(sp_UI_CursorOutlineInv,  ":UI:CursorOutlineInv")
stab_x(sp_UI_CursorPink,        ":UI:CursorPink")
stab_x(sp_UI_CursorRed,         ":UI:CursorRed")
stab_x(sp_UI_CursorWhite,       ":UI:CursorWhite")
stab_x(sp_UI_InvSel,            ":UI:InvSel")
stab_x(sp_UI_LogList,           ":UI:LogList")
stab_x(sp_UI_MagicSelectBack,   ":UI:MagicSelectBack")
stab_x(sp_UI_TextBoxBack,       ":UI:TextBoxBack")
stab_x(sp_UI_bip,               ":UI:bip")
stab_x(sp_lfiles_Cyberspace,    "lfiles/Cyberspace.txt")
stab_x(sp_lmusic_DOGS,          "lmusic/DOGS.ogg")
stab_x(sp_lmusic_Unce,          "lmusic/Unce.ogg")
stab_x(sp_lsounds_Silence,      "lsounds/Silence")
stab_x(sp_star,                 "*")

/* Sounds */
stab_x(ss_amb_rain,                 "amb/rain")
stab_x(ss_amb_wind,                 "amb/wind")
stab_x(ss_enemies_boss_talk,        "enemies/boss/talk")
stab_x(ss_enemies_phantom_escape,   "enemies/phantom/escape")
stab_x(ss_enemies_phantom_spawned,  "enemies/phantom/spawned")
stab_x(ss_marathon_pickup,          "marathon/pickup")
stab_x(ss_misc_telein,              "misc/telein")
stab_x(ss_misc_teleout,             "misc/teleout")
stab_x(ss_player_YOUVEGOTMAIL,      "player/YOUVEGOTMAIL")
stab_x(ss_player_adren_inj,         "player/adren/inj")
stab_x(ss_player_adren_ready,       "player/adren/ready")
stab_x(ss_player_cbi_auto_invalid,  "player/cbi/auto/invalid")
stab_x(ss_player_cbi_dlgopen,       "player/cbi/dlgopen")
stab_x(ss_player_cbi_find,          "player/cbi/find")
stab_x(ss_player_cbi_finddone,      "player/cbi/finddone")
stab_x(ss_player_cbi_findfail,      "player/cbi/findfail")
stab_x(ss_player_cbi_invcur,        "player/cbi/invcur")
stab_x(ss_player_cbi_invmov,        "player/cbi/invmov")
stab_x(ss_player_cbi_invrem,        "player/cbi/invrem")
stab_x(ss_player_cbi_keypress,      "player/cbi/keypress")
stab_x(ss_player_cbi_mail,          "player/cbi/mail")
stab_x(ss_player_cbi_scroll,        "player/cbi/scroll")
stab_x(ss_player_cbi_scrollend,     "player/cbi/scrollend")
stab_x(ss_player_death1,            "player/death1")
stab_x(ss_player_doublejump,        "player/doublejump")
stab_x(ss_player_levelup,           "player/levelup")
stab_x(ss_player_manafull,          "player/manafull")
stab_x(ss_player_pickup_item,       "player/pickup/item")
stab_x(ss_player_pickup_upgrbody,   "player/pickup/upgrbody")
stab_x(ss_player_pickup_upgrextr,   "player/pickup/upgrextr")
stab_x(ss_player_pickup_upgrweap,   "player/pickup/upgrweap")
stab_x(ss_player_rarmor_mode,       "player/rarmor/mode")
stab_x(ss_player_rocketboost,       "player/rocketboost")
stab_x(ss_player_score,             "player/score")
stab_x(ss_player_slide,             "player/slide")
stab_x(ss_player_trmopen,           "player/trmopen")
stab_x(ss_player_trmswitch,         "player/trmswitch")
stab_x(ss_player_zoomin,            "player/zoomin")
stab_x(ss_player_zoomout,           "player/zoomout")
stab_x(ss_weapons_cercle_attack,    "weapons/cercle/attack")
stab_x(ss_weapons_cercle_begin,     "weapons/cercle/begin")
stab_x(ss_weapons_rifle_firemode,   "weapons/rifle/firemode")
stab_x(ss_weapons_rocket_mark,      "weapons/rocket/mark")
stab_x(ss_weapons_subweapon_charge, "weapons/subweapon/charge")

#undef stab_x
#elif !defined(m_stab_h)
#define m_stab_h

#define stab_x(n, s) extern str n;
#include "m_stab.h"

#define Str(n, s) static str const n = s
#define StrAry(n, ...) static str const n[] = {__VA_ARGS__}

#endif
