/* ---------------------------------------------------------------------------|
 *
 * This file was generated by upgc.
 * Edit only if you aren't going to recompile.
 *
 * ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison Sanderson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 */


#include "u_func_beg.h"

Case(HeadsUpDisM)
   A(HeadsUpDisM)
   D(HeadsUpDisM)
   R(HeadsUpDisM)Case(HeadsUpDisC)
   A(HeadsUpDisC)
   D(HeadsUpDisC)
   R(HeadsUpDisC)Case(HeadsUpDisI)
   A(HeadsUpDisI)
   D(HeadsUpDisI)
   R(HeadsUpDisI)Case(HeadsUpDisD)
   A(HeadsUpDisD)
   D(HeadsUpDisD)
   R(HeadsUpDisD)Case(Zoom)
   D(Zoom)
   U(Zoom)
   R(Zoom)Case(VitalScan)
   U(VitalScan)
   R(VitalScan)Case(ReflexWetw)
   A(ReflexWetw)
   D(ReflexWetw)
   U(ReflexWetw)Case(JetBooster)
   A(JetBooster)
   U(JetBooster)
   R(JetBooster)Case(CyberLegs)
   A(CyberLegs)
   D(CyberLegs)
   U(CyberLegs)Case(ReactArmor)
   D(ReactArmor)
   R(ReactArmor)Case(DefenseNuke)
   E(DefenseNuke)Case(Adrenaline)
   U(Adrenaline)
   R(Adrenaline)Case(Magic)
   U(Magic)
   R(Magic)Case(StealthSys)
   D(StealthSys)
   U(StealthSys)Case(Subweapons)
   U(Subweapons)
   R(Subweapons)Case(AutoReload)
   A(AutoReload)
   D(AutoReload)Case(RifleModes)
   D(RifleModes)
   R(RifleModes)Case(HomingRPG)
   U(HomingRPG)Case(PunctCannon)
   D(PunctCannon)Case(7777777)
   A(7777777)
   D(7777777)
   U(7777777)Case(lolsords)
   A(lolsords)
   D(lolsords)
   U(lolsords)Case(Goldeneye)
   U(Goldeneye)Case(Implying)
   U(Implying)Case(UNCEUNCE)
   A(UNCEUNCE)
   D(UNCEUNCE)
   U(UNCEUNCE)Case(InstaDeath)
   U(InstaDeath)

#include "u_func_end.h"

/* EOF */
