class Lith_ScoreItem : Lith_BasicPickup
{
   private meta int m_score;

   property Score: m_score;

   default
   {
      Lith_BasicPickup.LogType msg_huds;
   }

   virtual bool Lith_CanGiveScore() {return true;}

   override bool TryPickup(in out Actor toucher)
   {
      if(Lith_CanGiveScore())
         toucher.ACS_ScriptCall("Lith_GiveScore", m_score);
      return Super.TryPickup(toucher);
   }

   states
   {
   Spawn:
      ABIP A -1;
      stop;
   }
}

// EOF
