class Lith_ScoreItem : Lith_BasicPickup
{
   private meta int m_Score;

   property Score: m_Score;

   default
   {
      Lith_BasicPickup.LogType msg_huds;
   }

   virtual bool Lith_CanGiveScore() {return true;}

   override void Lith_OnPickup(Actor mo)
   {
      if(Lith_CanGiveScore()) mo.ACS_ScriptCall("Lith_GiveScore", m_Score);
      Super.Lith_OnPickup(mo);
   }

   states
   {
   Spawn:
      ABIP A -1;
      stop;
   }
}

// EOF
