// Distributed under the CC0 public domain license.
// By Alison Sanderson. Attribution is encouraged, though not required.
// See licenses/cc0.txt for more information.

extend class Lith_HERMES;

static clearscope int FindLump(string name)
{
   return Wads.CheckNumForFullName(name);
}

static clearscope string ReadLump(int lump)
{
   let s = Wads.ReadLump(lump);
   s.Replace("\\c", "\c");
   return s;
}

// EOF
