// This file was generated by decompat.
// Edit only if you aren't going to recompile.

// This file was generated by wepc.
// Edit only if you aren't going to recompile.

enum WeaponNum
{
   weapon_min = 1,
   weapon_unknown = 0,

   weapon_cfist,
   weapon_missile,
   weapon_plasmadiff,
   weapon_fist,
   weapon_pistol,
   weapon_revolver,
   weapon_shotgun,
   weapon_lazshotgun,
   weapon_ssg,
   weapon_rifle,
   weapon_sniper,
   weapon_launcher,
   weapon_plasma,
   weapon_bfg,
   weapon_c_fist,
   weapon_c_mateba,
   weapon_c_rifle,
   weapon_c_spas,
   weapon_c_smg,
   weapon_c_sniper,
   weapon_c_plasma,
   weapon_c_shipgun,
   weapon_c_blade,
   weapon_c_delear,
   weapon_c_fire,
   weapon_c_rend,
   weapon_c_hulgyon,
   weapon_c_starshot,
   weapon_c_cercle,
   weapon_d_700e,
   weapon_d_4bore,
   weapon_d_launcher,
   weapon_d_minigun,
   weapon_d_rocket,
   weapon_d_fatmac,
   weapon_d_railgun,
   weapon_wings,

   weapon_max
};

enum WeaponName
{
   wepnam_fist,
   wepnam_chainsaw,
   wepnam_pistol,
   wepnam_shotgun,
   wepnam_supershotgun,
   wepnam_chaingun,
   wepnam_rocketlauncher,
   wepnam_plasmarifle,
   wepnam_bfg9000,

   wepnam_max,
};

enum RifleMode
{
   rifle_firemode_auto,
   rifle_firemode_grenade,
   rifle_firemode_burst,
   rifle_firemode_max
};

// EOF
