// This file was generated by decompat.
// Edit only if you aren't going to recompile.

// This file was generated by upgc.
// Edit only if you aren't going to recompile.

enum Lith_UpgradeName
{
   UPGR_HeadsUpDisp,
   UPGR_HeadsUpDis2,
   UPGR_HeadsUpDis3,
   UPGR_JetBooster,
   UPGR_ReflexWetw,
   UPGR_Zoom,
   UPGR_VitalScan,
   UPGR_CyberLegs,
   UPGR_ReactArmor,
   UPGR_ReactArmor2,
   UPGR_DefenseNuke,
   UPGR_Adrenaline,
   UPGR_Magic,
   UPGR_SoulCleaver,
   UPGR_StealthSys,
   UPGR_Subweapons,
   UPGR_AutoReload,
   UPGR_AutoPistol,
   UPGR_PlasPistol,
   UPGR_GaussShotty,
   UPGR_PoisonShot,
   UPGR_RifleModes,
   UPGR_LaserRCW,
   UPGR_ChargeRPG,
   UPGR_HomingRPG,
   UPGR_PlasLaser,
   UPGR_PartBeam,
   UPGR_PunctCannon,
   UPGR_OmegaRail,
   UPGR_Mateba_A,
   UPGR_ShockRif_A,
   UPGR_ShockRif_B,
   UPGR_SPAS_A,
   UPGR_SPAS_B,
   UPGR_SMG_A,
   UPGR_SMG_B,
   UPGR_SMG_C,
   UPGR_IonRifle_A,
   UPGR_IonRifle_B,
   UPGR_CPlasma_A,
   UPGR_ShipGun_A,
   UPGR_ShipGun_B,
   UPGR_TorgueMode,
   UPGR_7777777,
   UPGR_lolsords,
   UPGR_Goldeneye,
   UPGR_DarkCannon,
   UPGR_Implying,
   UPGR_UNCEUNCE,
   UPGR_InstaDeath,
   UPGR_BASE_MAX
};

// EOF
