// This file was generated by upgc.
// Edit only if you aren't going to recompile.
#include "u_func_beg.h"

Case(HeadsUpDisp)
   A(HeadsUpDisp)
   D(HeadsUpDisp)
   R(HeadsUpDisp)

Case(HeadsUpDis2)
   A(HeadsUpDis2)
   D(HeadsUpDis2)
   R(HeadsUpDis2)

Case(HeadsUpDis3)
   A(HeadsUpDis3)
   D(HeadsUpDis3)
   R(HeadsUpDis3)

Case(JetBooster)
   A(JetBooster)
   U(JetBooster)
   R(JetBooster)

Case(ReflexWetw)
   A(ReflexWetw)
   D(ReflexWetw)
   U(ReflexWetw)

Case(Zoom)
   D(Zoom)
   U(Zoom)
   R(Zoom)

Case(VitalScan)
   U(VitalScan)
   R(VitalScan)

Case(CyberLegs)
   A(CyberLegs)
   D(CyberLegs)
   U(CyberLegs)

Case(ReactArmor)
   D(ReactArmor)
   R(ReactArmor)

Case(DefenseNuke)
   E(DefenseNuke)

Case(Adrenaline)
   U(Adrenaline)
   R(Adrenaline)

Case(Magic)
   U(Magic)
   R(Magic)

Case(StealthSys)
   D(StealthSys)
   U(StealthSys)

Case(Subweapons)
   U(Subweapons)
   R(Subweapons)

Case(AutoReload)
   A(AutoReload)
   D(AutoReload)

Case(RifleModes)
   D(RifleModes)
   R(RifleModes)

Case(HomingRPG)
   U(HomingRPG)

Case(PunctCannon)
   D(PunctCannon)

Case(7777777)
   A(7777777)
   D(7777777)
   U(7777777)

Case(lolsords)
   A(lolsords)
   D(lolsords)
   U(lolsords)

Case(Goldeneye)
   U(Goldeneye)

Case(Implying)
   U(Implying)

Case(UNCEUNCE)
   A(UNCEUNCE)
   D(UNCEUNCE)
   U(UNCEUNCE)

Case(InstaDeath)
   U(InstaDeath)

#include "u_func_end.h"

// EOF
