/* ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison G. Watson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 */

class Lith_CameraHax : Actor
{
   default
   {
      Radius 2;
      Height 2;

      +NOTIMEFREEZE
      +NOINTERACTION
   }
}

class Lith_TimeHax  : PowerTimeFreezer {default {Powerup.Duration   1;}}
class Lith_TimeHax2 : PowerTimeFreezer {default {Powerup.Duration -80;}}

class Lith_PlayerBox : Actor
{
   default
   {
      Radius 16;
      Height 56;

      +NOTIMEFREEZE
      +NOGRAVITY
      +NOBLOCKMAP
      +NOCLIP
   }

   states
   {
   Spawn:
      TNT1 A 1;
      stop;
   }
}

/* EOF */
