/* ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison Sanderson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 */

#include "lzscript/Monsters/Base.zsc"

#include "lzscript/Monsters/Heretic.zsc"

#include "lzscript/Monsters/Doom/BossBrain.zsc"

#include "lzscript/Monsters/Doom/1_ChaingunGuy.zsc"
#include "lzscript/Monsters/Doom/1_Imp.zsc"
#include "lzscript/Monsters/Doom/1_ShotgunGuy.zsc"
#include "lzscript/Monsters/Doom/1_ZombieMan.zsc"

#include "lzscript/Monsters/Doom/2_Demon.zsc"
#include "lzscript/Monsters/Doom/2_LostSoul.zsc"
#include "lzscript/Monsters/Doom/2_Spectre.zsc"

#include "lzscript/Monsters/Doom/3_Arachnotron.zsc"
#include "lzscript/Monsters/Doom/3_Baron.zsc"
#include "lzscript/Monsters/Doom/3_Cacodemon.zsc"
#include "lzscript/Monsters/Doom/3_Knight.zsc"
#include "lzscript/Monsters/Doom/3_Mancubus.zsc"
#include "lzscript/Monsters/Doom/3_Revenant.zsc"

#include "lzscript/Monsters/Doom/4_Archvile.zsc"
#include "lzscript/Monsters/Doom/4_PainElemental.zsc"

#include "lzscript/Monsters/Doom/5_Cyberdemon.zsc"
#include "lzscript/Monsters/Doom/5_SpiderMastermind.zsc"

#include "lzscript/Monsters/Lithium/Phantom.zsc"

#include "lzscript/Monsters/Lithium/6_Archangel.zsc"
#include "lzscript/Monsters/Lithium/6_Isaac.zsc"
#include "lzscript/Monsters/Lithium/6_James.zsc"
#include "lzscript/Monsters/Lithium/6_Johnson.zsc"
#include "lzscript/Monsters/Lithium/6_Makarov.zsc"
#include "lzscript/Monsters/Lithium/6_Michael.zsc"

#include "lzscript/Monsters/Lithium/TitleMap.zsc"
#include "lzscript/Monsters/Lithium/TitleMarine.zsc"
#include "lzscript/Monsters/Lithium/MapMarine.zsc"

/* EOF */
