/* ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison Sanderson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 */

#include "lzscript/People/Base.zsc"
#include "lzscript/People/AdvMarine.zsc"
#include "lzscript/People/People.zsc"

/* EOF */
