/* ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison Sanderson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 */

class Lith_AdviceObject : Actor
{
   default
   {
      /*$Category "Decoration" */

      Height 32;
      Radius 20;
      Scale 0.7;
   }

}

/* EOF */
