// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │             Distributed under the CC0 public domain license.             │
// │   By Alison G. Watson. Attribution is encouraged, though not required.   │
// │                See licenses/cc0.txt for more information.                │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯

class Lith_BoomBarrel : ExplosiveBarrel {
   default {
      DeathSound "misc/booom";
   }
}

class Lith_ExplosiveBarrel : ExplosiveBarrel replaces ExplosiveBarrel;

default {
   Health 60;
   PainChance 255;
   PainSound "misc/barrel/hit";
   DeathSound "explosion";
   +CastSpriteShadow
}

states
{
Spawn:
   #DBA ABCDEFGHIJKLM 2;
   loop;
Pain:
   #DBA N 5 A_Pain;
   goto Spawn;
Death:
   #DBA OP 5;
   #DBA Q 3 bright;
   #DBA R 2 bright A_Scream;
   #DBA S 3 bright A_Explode;
   #DBA TUV 4 bright;
   #DBA W 3 bright;
   TNT1 A 10;
   TNT1 A 1050 A_BarrelDestroy;
   TNT1 A 5 A_Respawn;
   wait;
}

/* EOF */
