/* ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison G. Watson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 */

class Lith_Chair : Actor;

default {
   Height 32;
   Radius 20;
   Scale 0.7;
}

states {
Spawn:
   CHAI A -1;
   stop;
}

/* EOF */
