enum
{
   log_default,
   log_min,
   log_allmap = log_min,
   log_armorbonus,
   log_backpack,
   log_berserk,
   log_bluearmor,
   log_blursphere,
   log_greenarmor,
   log_healthbonus,
   log_infrared,
   log_invulnerability,
   log_medikit,
   log_megasphere,
   log_radsuit,
   log_soulsphere,
   log_stimpack,
   log_redcard,
   log_bluecard,
   log_yellowcard,
   log_redskull,
   log_blueskull,
   log_yellowskull,
   log_doggosphere,
   log_dogs,
   log_clip,
   log_clipbox,
   log_shell,
   log_shellbox,
   log_rocket,
   log_rocketbox,
   log_cell,
   log_cellbox,
   log_max
};

// EOF

