#include "lith_bip.h"
#include "lith_pdata.h"

struct page_initializer const bip_pages[] = {
   {.category = BIPC_WEAPONS},
   {pcl_outcasts, "ChargeFist", {"KSKK"}},

   {pcl_marine, "Pistol",          {"Omakeda"}},
   {pcl_marine, "Shotgun",         {"Omakeda"}},
   {pcl_marine, "ShotgunUpgr",     {"Shotgun", "AOF", "DurlaPrime"}},
   {pcl_marine, "ShotgunUpg2",     {"Shotgun"}},
   {pcl_marine, "SuperShotgun",    {"ChAri"}},
   {pcl_marine, "CombatRifle",     {"AllPoint"}},
   {pcl_marine, "RifleUpgr",       {"CombatRifle"}},
   {pcl_marine, "RifleUpg2",       {"CombatRifle", "Semaphore"}},
   {pcl_marine, "GrenadeLauncher", {"Sym43"}},
   {pcl_marine, "LauncherUpgr",    {"GrenadeLauncher", "UnrealArms"}},
   {pcl_marine, "LauncherUpg2",    {"GrenadeLauncher", "Sym43"}},
   {pcl_marine, "PlasmaRifle",     {"AllPoint", "MDDO"}},
   {pcl_marine, "PlasmaUpgr",      {"PlasmaRifle"}},
   {pcl_marine, "PlasmaUpg2",      {"PlasmaRifle", "Semaphore"}},
   {pcl_marine, "BFG9000",         {"Cid"}},
   {pcl_marine, "CannonUpgr",      {"BFG9000", "SuperDimension"}},
   {pcl_marine, "CannonUpg2",      {"BFG9000"}},

   {pcl_cybermage, "Mateba",        {"AOF"}},
   {pcl_cybermage, "MatebaUpgr",    {"AOF", "Algidistari"}},
   {pcl_cybermage, "ShockRifle"},
   {pcl_cybermage, "SPAS",          {"AOF", "Newvec"}},
   {pcl_cybermage, "SPASUpgr"},
   {pcl_cybermage, "SPASUpg2"},
   {pcl_cybermage, "SMG",           {"Omakeda", "Sym43"}},
   {pcl_cybermage, "SMGUpgr"},
   {pcl_cybermage, "SMGUpg2"},
   {pcl_cybermage, "SMGUpg3"},
   {pcl_cybermage, "IonRifle",      {"KSKK"}},
   {pcl_cybermage, "IonRifleUpgr"},
   {pcl_cybermage, "IonRifleUpg2"},
   {pcl_cybermage, "CPlasmaRifle",  {"AllPoint", "MDDO"}},
   {pcl_cybermage, "CPlasmaUpgr"},
   {pcl_cybermage, "StarDestroyer", {"Hell"}},
   {pcl_cybermage, "ShipGunUpgr"},
   {pcl_cybermage, "ShipGunUpg2"},

   {pcl_cybermage, "Blade"},
   {pcl_cybermage, "Delear"},
   {pcl_cybermage, "Fire"},
   {pcl_cybermage, "Rend"},
   {pcl_cybermage, "Hulgyon"},
   {pcl_cybermage, "StarShot"},
   {pcl_cybermage, "Cercle"},

   {pcl_outcasts, "Revolver",       {"Earth"}},
   {pcl_outcasts, "LazShotgun",     {"Earth"}},
   {pcl_outcasts, "SniperRifle",    {"Facer"}},
   {pcl_outcasts, "MissileLauncher"},
   {pcl_outcasts, "PlasmaDiffuser", {"Sym43", "MDDO", "Semaphore"}},

   {.category = BIPC_ENEMIES},
   {pcl_any, "ZombieMan"},
   {pcl_any, "ShotgunGuy"},
   {pcl_any, "ChaingunGuy"},

   {pcl_any, "Imp"},
   {pcl_any, "Demon"},
   {pcl_any, "Spectre"},

   {pcl_any, "LostSoul"},
   {pcl_any, "Mancubus"},
   {pcl_any, "Arachnotron"},
   {pcl_any, "Cacodemon"},

   {pcl_any, "HellKnight"},
   {pcl_any, "BaronOfHell"},
   {pcl_any, "Revenant"},

   {pcl_any, "PainElemental"},
   {pcl_any, "Archvile"},
   {pcl_any, "SpiderMastermind"},
   {pcl_any, "Cyberdemon"},

   {pcl_any, "Phantom"},
   {pcl_any, "IconOfSin"},

   {.category = BIPC_UPGRADES},
   {pcl_marine, "HeadsUpDisp", {"OFMD"}},
   {pcl_marine, "JetBooster",  {"OFMD"}},
   {pcl_marine, "ReflexWetw",  {"OFMD"}},
   {pcl_marine, "CyberLegs",   {"OFMD"}},
   {pcl_marine, "Yh0",         {"DurlaPrime"}},
   {pcl_marine, "DefenseNuke", {"OFMD"}},
   {pcl_marine, "Adrenaline",  {"KSKK"}},

   {pcl_cybermage, "HeadsUpDispJem"},
   {pcl_cybermage, "ReflexWetwJem"},
   {pcl_cybermage, "Magic"},
   {pcl_cybermage, "SoulCleaver"},

   {pcl_outcasts, "VitalScanner", {"KSKK"}},
   {pcl_outcasts, "AutoReload",   {"KSKK"}},

   {.category = BIPC_PLACES},
   {pcl_any, "AetosVi"},
   {pcl_any, "Algidistari"},
   {pcl_any, "ChAri"},
   {pcl_any, "DurlaPrime",     {"Earth", "AetosVi"}},
   {pcl_any, "Earth"},
   {pcl_any, "Hell"},
   {pcl_any, "Mars"},
   {pcl_any, "OmicronXevv"},
   {pcl_any, "SuperDimension", {"BFG9000", "SIGFPE"}},

   {.category = BIPC_CORPORATIONS},
   {pcl_any,       "AllPoint"},
   {pcl_marine,    "AOF"},
   {pcl_cybermage, "AOFJem"},
   {pcl_any,       "Cid",        {"SuperDimension", "Earth"}},
   {pcl_any,       "Facer"},
   {pcl_any,       "KSKK",       {"Earth"}},
   {pcl_any,       "MDDO",       {"Mars", "OFMD"}},
   {pcl_any,       "Newvec",     {"Earth"}},
   {pcl_any,       "OFMD"},
   {pcl_any,       "Omakeda",    {"Earth"}},
   {pcl_any,       "Semaphore",  {"OmicronXevv"}},
   {pcl_any,       "Sym43",      {"AetosVi"}},
   {pcl_any,       "UnrealArms", {"AetosVi"}},

   {.category = BIPC_EXTRA},
   {pcl_any, "Extra1"},
   {pcl_any, "Extra2"},
   {pcl_any, "Extra3"},
   {pcl_any, "Extra4"},
   {pcl_any, "Extra5"},

   {},
};

// EOF
