// Distributed under the CC0 public domain license.
// By Alison Sanderson. Attribution is encouraged, though not required.
// See licenses/cc0.txt for more information.

class Lith_XH_Spectre : Lith_Spectre
{
}

class Lith_Spectre : Lith_Demon replaces Spectre;

default
{
   Lith_Monster.Score Score_Spectre;
   SeeSound "";
   RenderStyle "Fuzzy";
   Alpha 0.5;
   Speed 11;
   Tag "Spectre";

   +SHADOW
}

// EOF
