// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │             Distributed under the CC0 public domain license.             │
// │   By Marrub / Alison.  Attribution is encouraged, though not required.   │
// │                See licenses/cc0.txt for more information.                │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯

class Lith_XH_Spectre : Lith_Spectre
{
}

class Lith_Spectre : Lith_Demon replaces Spectre;

default
{
   Alpha       0.5;
   RenderStyle "Fuzzy";
   Speed       11;
   Species     "Lith_Demon";

   SeeSound "";

   HitObituary "$OB_DEMONHIT";
   Tag         "$LITH_INFO_SHORT_Spectre";

   +SHADOW
}

/* EOF */
