/* ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison Sanderson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 */

class Lith_CyberRocket : Lith_Explosive
{
   default
   {
      DamageFunction 15 * Random(1, 8);
      DamageType     "Shrapnel";
      Height         4;
      Radius         8;
      Scale          0.75;
      Speed          25;

      Obituary "$OB_MPROCKET";

      Projectile;
      +DEHEXPLOSION
      +ROCKETTRAIL
   }

   states
   {
   Spawn:
      MISL A 1 bright;
      loop;
   Death:
      TNT1 A 0 A_Explode(96);
      TNT1 A 0 {if(target) target = target.target;}
      TNT1 A 0 Lith_A_DoExplosion;
      stop;
   }
}

class Lith_XH_Cyberdemon : Lith_Cyberdemon
{
   void Lith_A_XH_CyberdemonShoot()
   {
      A_StartSound("enemies/cyberdemon/fire", lch_weapon);
      A_SpawnProjectile("Lith_CyberRocket", 40, -13, frandom(-15, 15), CMF_OFFSETPITCH|CMF_BADPITCH, frandom(-5, 5));
   }

   states
   {
   Missile:
      CYBR E 2 A_FaceTarget;
      CYBR E 0 A_StartSound("enemies/cyberdemon/ready", lch_weapon2);
      CYBR E 12 A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      CYBR F 3 bright Lith_A_XH_CyberdemonShoot;
      CYBR E 1 bright A_FaceTarget;
      goto See;
   }
}

class Lith_Cyberdemon : Lith_Monster replaces Cyberdemon;

default
{
   Health           5000;
   Height           110;
   Mass             5000;
   MinMissileChance 160;
   Radius           40;
   Speed            16;

   ActiveSound "cyber/active";
   DeathSound  "cyber/death";
   PainSound   "cyber/pain";
   SeeSound    "cyber/sight";

   Obituary "$OB_CYBORG";
   Tag      "Cyber-Demon";

   +BOSS
   +BOSSDEATH
   +DONTMORPH
   +FLOORCLIP
   +MISSILEEVENMORE
   +MISSILEMORE
   +NORADIUSDMG
}

void Lith_A_CyberdemonShoot()
{
   A_StartSound("enemies/cyberdemon/fire", lch_weapon);
   A_SpawnProjectile("Lith_CyberRocket", 40, -13, 0, CMF_BADPITCH);
}

states
{
Spawn:
   CYBR AB 10 A_Look;
   loop;

See:
   CYBR A 3 A_Hoof;
   CYBR ABBCC 3 A_Chase;
   CYBR D 3 A_Metal;
   CYBR D 3 A_Chase;
   loop;

Missile:
   CYBR E 2 A_FaceTarget;
   CYBR E 0 A_StartSound("enemies/cyberdemon/ready", lch_weapon2);
   CYBR E 12 A_FaceTarget;
   CYBR F 3 bright Lith_A_CyberdemonShoot;
   CYBR E 1 bright A_FaceTarget;
   CYBR F 3 bright Lith_A_CyberdemonShoot;
   CYBR E 1 bright A_FaceTarget;
   CYBR F 3 bright Lith_A_CyberdemonShoot;
   CYBR E 1 bright A_FaceTarget;
   CYBR F 3 bright Lith_A_CyberdemonShoot;
   CYBR E 1 bright A_FaceTarget;
   CYBR F 3 bright Lith_A_CyberdemonShoot;
   CYBR E 1 bright A_FaceTarget;
   CYBR F 3 bright Lith_A_CyberdemonShoot;
   CYBR E 1 bright A_FaceTarget;
   goto See;

Death:
   CYBR H -1;
Crash:
   CYBR H 10;
   CYBR I 10 Lith_A_Die;
   CYBR JKL 10;
   CYBR M 10;
   CYBR NO 10;
   CYBR P 30;
   CYBR P -1 A_BossDeath;
   stop;
}

/* EOF */
