#!/usr/bin/env ruby
## Distributed under the CC0 public domain license.
## By Alison Sanderson. Attribution is encouraged, though not required.
## See licenses/cc0.txt for more information.
## DeCompat: ZScript ↔ C shared syntax preprocessor.

def writehead out
   out.write "// This file was generated by decompat.\n"
   out.write "// Edit only if you aren't going to recompile.\n\n"
end

def tozsc lns, out
   writehead out

   for ln in lns
      out.write ln.chomp.sub(/enum \/\/ /, "enum ") + ?\n
   end
end

for arg in ARGV
   lns = open(arg, "rt").readlines()
   zscs = []
   loop do
      ln = lns.shift
      if ln.start_with? "// zsc output: "
         zscs << ln[15..-1].chomp
      else
         break
      end
   end
   for zsc in zscs
      tozsc lns, open(zsc, "wt")
   end
end

## EOF
