#!/usr/bin/env ruby
## Copyright © 2018 Alison Sanderson, all rights reserved.
## HashFS: Compile a directory structure into an enumerated list.

require 'fileutils'

def run of, dir
   of.puts <<~_end_
   // This file was generated by hashfs.
   // Edit only if you aren't going to recompile.
   [enu default]
   _end_

   re = /#{Regexp.escape dir}\/(.+)\.png/
   Dir.glob "#{dir}/**/*.png" do |item|
      unless item.include? "/Font/"
         m = re.match item
         of.puts "\":#{m[1].gsub '/', ':'}\" = \"#{item}\";"
      end
   end
end

for arg in ARGV
   fname, dir = arg.split ","
   run open(fname, "w"), dir
end
