#!/usr/bin/env ruby
LICENSE = <<_end_
 * ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison Sanderson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
_end_
##
## Compile a directory structure into an enumerated list.
##
## ---------------------------------------------------------------------------|

require 'fileutils'

def run of, pkdir, dir
   of.puts <<_end_
/* ---------------------------------------------------------------------------|
 *
 * This file was generated by hashfs.
 * Edit only if you aren't going to recompile.
 *
#{LICENSE}
 */

[enu default]
_end_

   pdir = "#{pkdir}#{dir}"
   re = /#{Regexp.escape pdir}\/(.+)\.png/
   Dir.glob "#{pdir}/**/*.png" do |item|
      unless item.include? "/Font/"
         m = re.match item
         of.puts %(":#{m[1].gsub ?/, ?:}" = "#{item.gsub pkdir, ""}";)
      end
   end
end

for arg in ARGV
   fname, pkdir, dir = arg.split ?:
   run open(fname, "w"), pkdir, dir
end
