// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │             Distributed under the CC0 public domain license.             │
// │   By Marrub / Alison.  Attribution is encouraged, though not required.   │
// │                See licenses/cc0.txt for more information.                │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯

class Lith_PlayerDeathParticle : Actor
{
   default
   {
      RenderStyle "Subtract";

      +THRUACTORS
      +NOGRAVITY
      +BOUNCEONWALLS
      +BOUNCEONCEILINGS
      +NOTELEPORT
      +BRIGHT
   }

   states
   {
   Spawn:
      TNT1 A random(3, 10);
      #EDE AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_SetScale(frandom(0.15, 0.2));
      #EDE A 1 A_FadeOut(0.01);
      wait;
   }
}

class Lith_PlayerDeathParticle2 : Actor
{
   default
   {
      RenderStyle "Subtract";
      Scale 0.2;

      +NOINTERACTION
      +BRIGHT
   }

   states
   {
   Spawn:
      TNT1 A random(3, 10);
      #EDE AAAA 12 A_FadeOut(0.1);
      #EDE AAAA 4 A_FadeOut(0.1);
      stop;
   }
}

/* EOF */
