// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │                     This file cannot be copyrighted.                     │
// │                                                                          │
// ├──────────────────────────────────────────────────────────────────────────┤
// │                                                                          │
// │ This file was generated by trie.                                         │
// │ Edit only if you aren't going to recompile.                              │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯


enum {
   _save_chunk_Lith,
   _save_chunk_agrp,
   _save_chunk_bipu,
   _save_chunk_intr,
   _save_chunk_note,
   _bipinfo_page_cl,
   _bipinfo_page_tag,
   _bipinfo_page_unl,
   _bipinfo_template_auto,
   _bipinfo_template_corporations,
   _bipinfo_template_enemies,
   _bipinfo_template_extra,
   _bipinfo_template_items,
   _bipinfo_template_mail,
   _bipinfo_template_places,
   _bipinfo_template_upgrades,
   _bipinfo_template_weapons,
   _bipinfo_template_yourself,
   _dlg_toplevel_dialogue,
   _dlg_toplevel_dialogue_names,
   _dlg_toplevel_program,
   _dlg_toplevel_program_names,
   _dlg_toplevel_terminal,
   _dlg_toplevel_terminal_names,
   _dlg_toplevel_var,
   _dlg_cond_class,
   _dlg_cond_item,
   _dlg_cond_var,
   _dlg_stmt_crawl,
   _dlg_stmt_fade_in,
   _dlg_stmt_fade_out,
   _dlg_stmt_icon,
   _dlg_stmt_if,
   _dlg_stmt_image,
   _dlg_stmt_info,
   _dlg_stmt_logoff,
   _dlg_stmt_logon,
   _dlg_stmt_mus_fade,
   _dlg_stmt_music,
   _dlg_stmt_name,
   _dlg_stmt_option,
   _dlg_stmt_page,
   _dlg_stmt_pict,
   _dlg_stmt_remote,
   _dlg_stmt_script,
   _dlg_stmt_teleport_interlevel,
   _dlg_stmt_teleport_intralevel,
   _dlg_stmt_text,
   _dlg_stmt_wait,
   _dlg_item_failure,
   _dlg_item_finished,
   _dlg_item_page,
   _dlg_item_page_names,
   _dlg_item_unfinished,
   _moninfo_preset_exp,
   _moninfo_preset_name,
   _moninfo_preset_scr,
   _moninfo_monster_exp,
   _moninfo_monster_filter,
   _moninfo_monster_hacks,
   _moninfo_monster_pre,
   _moninfo_monster_scr,
   _moninfo_monster_type,
   _moninfo_hack_ch,
   _moninfo_toplevel_presets
};

stkcall
i32 P_SaveChunkName(register cstr s);
stkcall
i32 BipInfo_Page_Name(register cstr s);
stkcall
i32 BipInfo_Template_Name(register cstr s);
stkcall
i32 Dlg_TopLevelName(register cstr s);
stkcall
i32 Dlg_CondName(register cstr s);
stkcall
i32 Dlg_StmtName(register cstr s);
stkcall
i32 Dlg_ItemName(register cstr s);
stkcall
i32 P_ClassToInt(register cstr s);
stkcall
i32 MonInfo_Preset_Name(register cstr s);
stkcall
i32 MonInfo_Monster_Name(register cstr s);
stkcall
i32 MonInfo_Monster_TypeName(register cstr s);
stkcall
i32 MonInfo_Monster_HackName(register cstr s);
stkcall
i32 MonInfo_Flag_Name(register cstr s);
stkcall
i32 MonInfo_TopLevelName(register cstr s);
stkcall
i32 Upgr_StrToEnum(register cstr s);

/* EOF */
