// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │                     This file cannot be copyrighted.                     │
// │                                                                          │
// ├──────────────────────────────────────────────────────────────────────────┤
// │                                                                          │
// │ This file was generated by verc.                                         │
// │ Edit only if you aren't going to recompile.                              │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯


#if defined(VERSION)
VERSION(1, 0, 0, 0, "", "Lithium")
VERSION(1, 1, 0, 0, "", "Lithium Chloride")
VERSION(1, 2, 0, 0, "", "Lithium Carbonate")
VERSION(1, 3, 0, 0, "", "Zabuyelite")
VERSION(1, 3, 1, 0, "", "LITHIUM - Hell Knights Insist On Dying")
VERSION(1, 4, 0, 0, "", "Lumate")
VERSION(1, 5, 0, 0, "a", "Pegmatite")
VERSION(1, 5, 0, 1, "a2", "Pegmatite")
VERSION(1, 5, 0, 2, "b", "Pegmatite")
VERSION(1, 5, 0, 3, "", "Pegmatite")
VERSION(1, 5, 1, 0, "", "Rubellite Pegmatite")
VERSION(1, 5, 2, 0, "", "Rubellite Pegmatite")
VERSION(1, 5, 3, 0, "", "Indicolite Pegmatite")
VERSION(1, 6, 0, 0, "", "Hyper-Dilithium")
VERSION(1, 6, 1, 0, "", "Hyper-Trilithium")
VERSION(1, 6, 2, 0, "", "Trilithionite")
VERSION(1, 6, 3, 0, "", "Trilithionite Red")
VERSION(1, 7, 0, 0, "b", "Yttrium Oxide")
VERSION(1, 7, 0, 1, "b2", "Yttrium Oxide")

#undef VERSION
#elif defined(LEGACYVERSION)
LEGACYVERSION(1000, vernum_1_0_0_0)
LEGACYVERSION(1100, vernum_1_1_0_0)
LEGACYVERSION(1200, vernum_1_2_0_0)
LEGACYVERSION(1300, vernum_1_3_0_0)
LEGACYVERSION(1310, vernum_1_3_1_0)
LEGACYVERSION(1400, vernum_1_4_0_0)
LEGACYVERSION(1501, vernum_1_5_0_0)
LEGACYVERSION(1502, vernum_1_5_0_1)
LEGACYVERSION(1503, vernum_1_5_0_2)
LEGACYVERSION(1504, vernum_1_5_0_3)
LEGACYVERSION(1510, vernum_1_5_1_0)
LEGACYVERSION(1520, vernum_1_5_2_0)
LEGACYVERSION(1530, vernum_1_5_3_0)
LEGACYVERSION(1600, vernum_1_6_0_0)
LEGACYVERSION(1610, vernum_1_6_1_0)
LEGACYVERSION(1620, vernum_1_6_2_0)
LEGACYVERSION(1630, vernum_1_6_3_0)

#undef LEGACYVERSION
#else
#define vernum_1_0_0_0 1000000
#define verstr_1_0_0_0 "1.0.0"
#define vernam_1_0_0_0 "1.0.0 (Lithium)"
#define vernum_1_1_0_0 1010000
#define verstr_1_1_0_0 "1.1.0"
#define vernam_1_1_0_0 "1.1.0 (Lithium Chloride)"
#define vernum_1_2_0_0 1020000
#define verstr_1_2_0_0 "1.2.0"
#define vernam_1_2_0_0 "1.2.0 (Lithium Carbonate)"
#define vernum_1_3_0_0 1030000
#define verstr_1_3_0_0 "1.3.0"
#define vernam_1_3_0_0 "1.3.0 (Zabuyelite)"
#define vernum_1_3_1_0 1030100
#define verstr_1_3_1_0 "1.3.1"
#define vernam_1_3_1_0 "1.3.1 (LITHIUM - Hell Knights Insist On Dying)"
#define vernum_1_4_0_0 1040000
#define verstr_1_4_0_0 "1.4.0"
#define vernam_1_4_0_0 "1.4.0 (Lumate)"
#define vernum_1_5_0_0 1050000
#define verstr_1_5_0_0 "1.5.0a"
#define vernam_1_5_0_0 "1.5.0a (Pegmatite)"
#define vernum_1_5_0_1 1050001
#define verstr_1_5_0_1 "1.5.0a2"
#define vernam_1_5_0_1 "1.5.0a2 (Pegmatite)"
#define vernum_1_5_0_2 1050002
#define verstr_1_5_0_2 "1.5.0b"
#define vernam_1_5_0_2 "1.5.0b (Pegmatite)"
#define vernum_1_5_0_3 1050003
#define verstr_1_5_0_3 "1.5.0"
#define vernam_1_5_0_3 "1.5.0 (Pegmatite)"
#define vernum_1_5_1_0 1050100
#define verstr_1_5_1_0 "1.5.1"
#define vernam_1_5_1_0 "1.5.1 (Rubellite Pegmatite)"
#define vernum_1_5_2_0 1050200
#define verstr_1_5_2_0 "1.5.2"
#define vernam_1_5_2_0 "1.5.2 (Rubellite Pegmatite)"
#define vernum_1_5_3_0 1050300
#define verstr_1_5_3_0 "1.5.3"
#define vernam_1_5_3_0 "1.5.3 (Indicolite Pegmatite)"
#define vernum_1_6_0_0 1060000
#define verstr_1_6_0_0 "1.6.0"
#define vernam_1_6_0_0 "1.6.0 (Hyper-Dilithium)"
#define vernum_1_6_1_0 1060100
#define verstr_1_6_1_0 "1.6.1"
#define vernam_1_6_1_0 "1.6.1 (Hyper-Trilithium)"
#define vernum_1_6_2_0 1060200
#define verstr_1_6_2_0 "1.6.2"
#define vernam_1_6_2_0 "1.6.2 (Trilithionite)"
#define vernum_1_6_3_0 1060300
#define verstr_1_6_3_0 "1.6.3"
#define vernam_1_6_3_0 "1.6.3 (Trilithionite Red)"
#define vernum_1_7_0_0 1070000
#define verstr_1_7_0_0 "1.7.0b"
#define vernam_1_7_0_0 "1.7.0b (Yttrium Oxide)"
#define vernum_1_7_0_1 1070001
#define verstr_1_7_0_1 "1.7.0b2"
#define vernam_1_7_0_1 "1.7.0b2 (Yttrium Oxide)"

#define vernum vernum_1_7_0_1
#define verstr verstr_1_7_0_1
#define vernam vernam_1_7_0_1
#if defined(ZscOn)
const LITH_VERNAM = vernam;
const LITH_VERNUM = vernum;
const LITH_VERSTR = verstr;
const LITH_VERSION = vernam
#ifndef NDEBUG
" ("
#ifdef RELEASE
"DEBUG"
#else
"DEV"
#endif
")"
#endif
;
#elif !defined(VER_DEFINES_ONLY)
i32 version_name_to_num(cstr s);
#endif
#endif

/* EOF */
