// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │                     This file cannot be copyrighted.                     │
// │                                                                          │
// ├──────────────────────────────────────────────────────────────────────────┤
// │                                                                          │
// │ This file was generated by upgc.                                         │
// │ Edit only if you aren't going to recompile.                              │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯


#ifdef A
#undef A
#define A(n) Fn(n, Activate)
#else
#define A(n)
#endif
#ifdef D
#undef D
#define D(n) Fn(n, Deactivate)
#else
#define D(n)
#endif
#ifdef U
#undef U
#define U(n) Fn(n, Update)
#else
#define U(n)
#endif
#ifdef E
#undef E
#define E(n) Fn(n, Enter)
#else
#define E(n)
#endif
#ifdef R
#undef R
#define R(n) Fn(n, Render)
#else
#define R(n)
#endif

Case(HeadsUpDisp)
   A(HeadsUpDisp)
   R(HeadsUpDisp)
Case(Flashlight)
   D(Flashlight)
   U(Flashlight)
   E(Flashlight)
Case(Zoom)
   D(Zoom)
   U(Zoom)
   R(Zoom)
Case(VitalScan)
   U(VitalScan)
   R(VitalScan)
Case(ReflexWetw)
   A(ReflexWetw)
   U(ReflexWetw)
Case(JetBooster)
   U(JetBooster)
Case(CyberLegs)
   U(CyberLegs)
Case(ReactArmor)
   D(ReactArmor)
   R(ReactArmor)
Case(ReactArmor2)
Case(DefenseNuke)
   E(DefenseNuke)
Case(Adrenaline)
   D(Adrenaline)
   U(Adrenaline)
Case(Magic)
   U(Magic)
   R(Magic)
Case(SoulCleaver)
Case(StealthSys)
   D(StealthSys)
   U(StealthSys)
Case(Subweapons)
   U(Subweapons)
   R(Subweapons)
   E(Subweapons)
Case(AutoReload)
Case(Pistol_A)
Case(Pistol_B)
Case(Shotgun_A)
Case(Shotgun_B)
Case(Rifle_A)
   D(Rifle_A)
   R(Rifle_A)
Case(Rifle_B)
Case(RPG_A)
Case(RPG_B)
   U(RPG_B)
Case(Plasma_A)
Case(Plasma_B)
Case(Cannon_A)
   D(Cannon_A)
Case(Cannon_B)
Case(Cannon_C)
Case(Mateba_A)
Case(ShockRif_A)
Case(ShockRif_B)
Case(SPAS_A)
Case(SPAS_B)
Case(SMG_A)
Case(SMG_B)
Case(SMG_C)
Case(IonRifle_A)
Case(IonRifle_B)
Case(CPlasma_A)
Case(ShipGun_A)
Case(ShipGun_B)
Case(TorgueMode)
Case(Seven7s)
   A(Seven7s)
   D(Seven7s)
   U(Seven7s)
Case(lolsords)
   A(lolsords)
   D(lolsords)
   U(lolsords)
Case(Goldeneye)
   U(Goldeneye)
Case(UNCEUNCE)
   A(UNCEUNCE)
   D(UNCEUNCE)
   U(UNCEUNCE)
Case(InstaDeath)
   U(InstaDeath)
Case(OneShot)


#undef A
#undef D
#undef U
#undef E
#undef R

/* EOF */
