// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │                     This file cannot be copyrighted.                     │
// │                                                                          │
// ├──────────────────────────────────────────────────────────────────────────┤
// │                                                                          │
// │ This file was generated by upgc.                                         │
// │ Edit only if you aren't going to recompile.                              │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯


#if defined(upgrade_x)
upgrade_x(HeadsUpDisp)
upgrade_x(Flashlight)
upgrade_x(Zoom)
upgrade_x(VitalScan)
upgrade_x(ReflexWetw)
upgrade_x(JetBooster)
upgrade_x(CyberLegs)
upgrade_x(ReactArmor)
upgrade_x(ReactArmor2)
upgrade_x(DefenseNuke)
upgrade_x(Adrenaline)
upgrade_x(Magic)
upgrade_x(SoulCleaver)
upgrade_x(StealthSys)
upgrade_x(Subweapons)
upgrade_x(AutoReload)
upgrade_x(Pistol_A)
upgrade_x(Pistol_B)
upgrade_x(Shotgun_A)
upgrade_x(Shotgun_B)
upgrade_x(Rifle_A)
upgrade_x(Rifle_B)
upgrade_x(RPG_A)
upgrade_x(RPG_B)
upgrade_x(Plasma_A)
upgrade_x(Plasma_B)
upgrade_x(Cannon_A)
upgrade_x(Cannon_B)
upgrade_x(Cannon_C)
upgrade_x(Mateba_A)
upgrade_x(ShockRif_A)
upgrade_x(ShockRif_B)
upgrade_x(SPAS_A)
upgrade_x(SPAS_B)
upgrade_x(SMG_A)
upgrade_x(SMG_B)
upgrade_x(SMG_C)
upgrade_x(IonRifle_A)
upgrade_x(IonRifle_B)
upgrade_x(CPlasma_A)
upgrade_x(ShipGun_A)
upgrade_x(ShipGun_B)
upgrade_x(TorgueMode)
upgrade_x(Seven7s)
upgrade_x(lolsords)
upgrade_x(Goldeneye)
upgrade_x(UNCEUNCE)
upgrade_x(InstaDeath)
upgrade_x(OneShot)

#undef upgrade_x
#elif !defined(upgc_header)
#define upgc_header

enum ZscName(UpgradeName) {
   #define upgrade_x(name) UPGR_##name,
   #include "u_names.h"
   UPGR_MAX
};

#endif
