class Lith_ShrapnelGun : Lith_DWeapon;

default
{
   Tag "$LITH_INFO_SHORT_ShrapnelGun";
   Weapon.SlotNumber 3;
   Weapon.SlotPriority 0.9;
}

states(Actor)
{
SpawnPickup:
   TNT1 A 0 Lith_A_SpawnPickup("Lith_SuperShotgunPickup");
   stop;
}

states(Weapon)
{
Ready:
   SHT2 A 1 Lith_A_Ready;
   loop;

Deselect:
   SHT2 AA 0 A_Lower;
   SHT2 A 1;
   loop;

Select:
   SHT2 AA 0 A_Raise;
   SHT2 A 1;
   loop;

Fire:
   goto Ready;
}

// EOF
