class Lith_DualRocket : Lith_DWeapon;

default
{
   Tag "$LITH_INFO_SHORT_DualRocket";
   Weapon.SlotNumber 5;
   Weapon.SlotPriority 1;
}

states(actor)
{
SpawnPickup:
   TNT1 A 0 Lith_A_SpawnPickup("Lith_RocketLauncherPickup");
   stop;
}

states(weapon)
{
Ready:
   GRLG A 1 Lith_A_Ready;
   loop;

Deselect:
   GRLG AA 0 A_Lower;
   GRLG A 1;
   loop;
Select:
   GRLG AA 0 A_Raise;
   GRLG A 1;
   loop;

Fire:
   goto Ready;
}

// EOF
