/* ---------------------------------------------------------------------------|
 *
 * Distributed under the CC0 public domain license.
 * By Alison G. Watson. Attribution is encouraged, though not required.
 * See licenses/cc0.txt for more information.
 *
 * ---------------------------------------------------------------------------|
 */

class Lith_MiniMissile : Lith_Explosive
{
   default
   {
      Scale 0.25;
      Radius 2;
      Height 2;
      Speed 20;
      Damage 5;
      DeathSound "weapons/missile/explode";
      Species "Lith_Player";
      DamageType "Shrapnel";

      Projectile;
      +DONTHARMSPECIES
      +ROCKETTRAIL
      +MTHRUSPECIES
      +EXPLODEONWATER
   }

   states
   {
   Spawn:
      MISL A 0;
      MISL A 0 A_StartSound("effects/rocket/fly", lch_body, CHANF_LOOP, 0.65);
   SpawnLoop:
      MISL A 1 bright;
      wait;
   Death:
      TNT1 A 0 A_Explode(32, 42);
      TNT1 A 0 Lith_A_DoExplosion(0.2);
      stop;
   }
}

/* EOF */
