// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │             Distributed under the CC0 public domain license.             │
// │   By Marrub / Alison.  Attribution is encouraged, though not required.   │
// │                See licenses/cc0.txt for more information.                │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯

class Lith_MiniMissile : Lith_Explosive;

default {
   Scale 0.25;
   Radius 2;
   Height 2;
   Speed 20;
   Damage 5;
   DamageType "Shrapnel";
   ExplosionDamage 32;
   ExplosionRadius 42;
   Lith_Explosive.ExplosionSound "weapons/missile/explode";
   Lith_Explosive.FxAmount 0.2;
   Projectile;
   +EXPLODEONWATER
}

override void markPrecacheSounds() {
   super.markPrecacheSounds();
   markSound("effects/rocket/fly");
}

states {
Spawn:
   MISL A 0;
   MISL A 0 A_StartSound("effects/rocket/fly", lch_body, CHANF_LOOP, 0.65);
SpawnLoop:
   MISL A 1 bright;
   wait;
Death:
   TNT1 A 0 {
      A_Explode(explosionDamage, explosionRadius, 0);
      Lith_A_ExplodeSound();
      return Lith_A_DoExplosion();
   }
   stop;
}

/* EOF */
