// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │             Distributed under the CC0 public domain license.             │
// │   By Alison G. Watson. Attribution is encouraged, though not required.   │
// │                See licenses/cc0.txt for more information.                │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯

class Lith_PunctuatorExplosion : Lith_Explosive {
   default {
      RenderStyle "Add";
      Alpha 0.3;
      Scale 0.9;
      Species "Lith_Player";
      DamageType "Shrapnel";

      +DONTHARMSPECIES
      +BLOODLESSIMPACT
      +NOINTERACTION
      +FORCERADIUSDMG
   }

   override void beginPlay() {
      super.beginPlay();
      /* !!!HACK!!! */
      target = players[consolePlayer].mo;
   }

   states {
   Spawn:
      TNT1 A 0;
      TNT1 AA 0 A_Explode(128, 128, 0);
      TNT1 A random(1, 5);
      TNT1 A 0 Lith_A_DoExplosion(0.5);
      stop;
   }
}

class Lith_PunctuatorPuff : Lith_Explosive {
   default {
      Species "Lith_Player";
      DamageType "Shrapnel";

      +DONTHARMSPECIES
      +NOINTERACTION
      +PUFFONACTORS
      +BLOODLESSIMPACT
      +MTHRUSPECIES
      +FORCERADIUSDMG
   }

   override void beginPlay() {
      super.beginPlay();
      /* !!!HACK!!! */
      target = players[consolePlayer].mo;
   }

   states {
   Spawn:
      TNT1 A 0;
      TNT1 AA 0 A_Explode(128, 128, 0);
      TNT1 A 0 Lith_A_ExplodeSound;
      TNT1 A 0 Lith_A_DoExplosion(2.0);
      stop;
   }
}

/* EOF */
