// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │             Distributed under the CC0 public domain license.             │
// │   By Alison G. Watson. Attribution is encouraged, though not required.   │
// │                See licenses/cc0.txt for more information.                │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯

class Lith_PunctuatorExplosion : Lith_Explosive {
   default {
      RenderStyle "Add";
      Alpha 0.3;
      Scale 0.9;
      DamageType "Shrapnel";
      Lith_Explosive.FxAmount 0.5;

      +BLOODLESSIMPACT
      +NOINTERACTION
      +FORCERADIUSDMG
   }

   states {
   Spawn:
      TNT1 A 0;
      TNT1 AA 0 A_Explode(explosionDamage, explosionRadius, xf_nosplash);
      TNT1 A random(1, 5);
      TNT1 A 0 Lith_A_DoExplosion;
      stop;
   }
}

class Lith_PunctuatorPuff : Lith_Explosive {
   default {
      DamageType "Shrapnel";
      Lith_Explosive.FxAmount 2.0;

      +NOINTERACTION
      +PUFFONACTORS
      +BLOODLESSIMPACT
      +FORCERADIUSDMG
   }

   states {
   Spawn:
      TNT1 A 0;
      TNT1 A 0 {
         A_Explode(explosionDamage, explosionRadius, 0);
         A_Explode(explosionDamage, explosionRadius, 0);
         Lith_A_ExplodeSound();
         return Lith_A_DoExplosion();
      }
      stop;
   }
}

/* EOF */
