class Lith_RifleGrenadeSmoke : Lith_Explosive
{
   default
   {
      RenderStyle "Add";
      Scale 0.15;
      Alpha 0.8;

      +NOINTERACTION
   }

   states
   {
   Spawn:
      TNT1 A 0;
      TNT1 A 0 {
         if(CheckMarathon()) return ResolveState("Marathon");
         else                return state(null);
      }
      SMOK ACDGHJKMPQ 1 bright;
      stop;
   Marathon:
      TNT1 A 2;
      MA7G HI 1 bright;
      MA7G JKLM 1;
      stop;
   }
}

class Lith_RifleGrenade : Lith_Explosive;

default
{
   Radius 8;
   Height 8;
   Speed 25;
   Damage 10;
   BounceType "Doom";
   BounceCount 2;
   Gravity 0.5;
   BounceSound "weapons/rifle/grenadebounce";
   Species "Lith_Player";
   DamageType "Shrapnel";

   Projectile;
   +MTHRUSPECIES
   +EXPLODEONWATER
   -NOGRAVITY
}

states
{
Spawn:
   SGRN A 2 bright A_SpawnItemEx("Lith_RifleGrenadeSmoke", -8, flags: SXF_TRANSFERPOINTERS);
   loop;
Death:
   TNT1 A 0 A_Explode();
   TNT1 A 0 Lith_A_DoExplosion;
   stop;
}

// EOF
