// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │             Distributed under the CC0 public domain license.             │
// │   By Marrub / Alison.  Attribution is encouraged, though not required.   │
// │                See licenses/cc0.txt for more information.                │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯

class Lith_RifleGrenadeSmoke : Actor {
   default {
      RenderStyle "Add";
      Scale 0.15;
      Alpha 0.8;
      +NoInteraction
   }

   override void tick() {
      if(!isFrozen()) {
         Lith_UTIL.stateTick(self);
      }
   }

   states {
   Spawn:
      TNT1 A 2;
      #ESM ACDGHJKMPQ 1 bright;
      stop;
   }
}

class Lith_RifleGrenadeSmokeMarathon : Lith_RifleGrenadeSmoke {
   states {
   Spawn:
      TNT1 A 2;
      MA7G HI 1 bright;
      MA7G JKLM 1;
      stop;
   }
}

class Lith_RifleGrenade : Lith_Explosive;

default {
   Radius 8;
   Height 8;
   Speed 25;
   Damage 10;
   BounceType "Doom";
   BounceCount 2;
   Gravity 0.5;
   BounceSound "weapons/rifle/grenadebounce";
   DamageType "Shrapnel";
   Projectile;
   +ExplodeOnWater
   -NoGravity
}

states {
Spawn:
   SGRN A 2 bright {
      if(checkMarathon()) {spawn("Lith_RifleGrenadeSmokeMarathon", pos);}
      else                {spawn("Lith_RifleGrenadeSmoke",         pos);}
   }
   loop;
}

/* EOF */
